version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: waste-management-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: waste_management_db
      MYSQL_USER: waste_user
      MYSQL_PASSWORD: waste_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: waste-management-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: waste_user
      PMA_PASSWORD: waste_password
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:






