spring:
  application:
    name: waste-management-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/waste_management_system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:altin}
    password: ${DB_PASSWORD:123qwe}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: false
    contexts: default

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
    expiration: 86400000 # 24 hours
  
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000}
    allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_HEADERS:*}
  
  mail:
    from: ${MAIL_FROM:noreply@wastemanagement.com}
  
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  
  backend:
    url: ${BACKEND_URL:http://localhost:8080}

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

logging:
  level:
    com.kosovo.wastemanagement: DEBUG
    org.springframework.security: DEBUG
    liquibase: DEBUG
    org.springframework.jdbc: DEBUG
